//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jominder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Developer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public double Maturity { get; set; }
        public string About { get; set; }
        public string Contact { get; set; }
        public string Location { get; set; }
        public string Portfolio { get; set; }
        public string Offer { get; set; }
    }
}
