//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jominder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LandOwner
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Location { get; set; }
        public bool Status { get; set; }
        public double Amount { get; set; }
        public string Demand { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public bool Verification { get; set; }
        public string RegNo { get; set; }
        public string Other { get; set; }
    }
}
